---
- name: Add Duo Key
  apt_key: url=https://duo.com/DUO-GPG-PUBLIC-KEY.asc state=present

- name: Add Duo Source
  template: src=duosecurity.list.j2 dest=/etc/apt/sources.list.d/duosecurity.list

- name: Install Duo Unix SSH Integration
  apt: name=duo-unix state=present update_cache=yes

- name: Install Duo config
  template: src=login_duo.conf.j2 dest=/etc/duo/login_duo.conf owner=sshd group=0 mode=0600

- name: Install Login Script
  copy: src=login_duo_session dest=/usr/sbin/login_duo_session mode=a+x

- name: Enable duo security for remote logins
  lineinfile: dest=/etc/ssh/sshd_config regexp=^ForceCommand line="ForceCommand /usr/sbin/login_duo_session"
  notify:
  - restart sshd

- name: Disable PermitTunnel and AllowTcpForwarding
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp=^{{ item.key }}
    line="{{ item.key }} {{ item.value }}"
    insertafter=EOF
  with_items:
    - { key: 'PermitTunnel', value: 'no' }
    - { key: 'AllowTcpForwarding', value: 'no' }
  notify: restart sshd
